-- Generated by verifier/associative_array_bridge.py from the reviewed Clang AST.
-- Trusted STL mapping: std::map<uint64_t,uint64_t> is a finite partial map;
-- insert_or_assign updates one key, find returns its iterator or end.
-- The mapping itself and the standard library contract are trust assumptions.
import Init.Omega

namespace Proofs.AssociativeArray

structure State where
  entries : Nat → Option Nat
  writes : Nat

def empty : State := ⟨fun _ => none, 0⟩

def set (s : State) (key value : Nat) : State :=
  ⟨fun k => if k = key then some value else s.entries k, s.writes + 1⟩

def get (s : State) (key : Nat) : Nat :=
  match s.entries key with
  | none => 0
  | some value => value

inductive Query where
  | set (key value : Nat)
  | get (key : Nat)

structure Result where
  state : State
  output : List Nat
  steps : Nat

def run : List Query → State → Result
  | [], s => ⟨s, [], 0⟩
  | Query.set key value :: qs, s =>
      let r := run qs (set s key value)
      ⟨r.state, r.output, r.steps + 1⟩
  | Query.get key :: qs, s =>
      let r := run qs s
      ⟨r.state, get s key :: r.output, r.steps + 1⟩

-- A charged upper bound for one STL map operation at most q updates in.
-- Its validity for C++ std::map is the documented STL complexity contract.
def unitCost (q : Nat) : Nat := 1 + Nat.log2 (q + 1)
def totalCost (q : Nat) : Nat := q * unitCost q
def extraSlots (q : Nat) : Nat := q

end Proofs.AssociativeArray
